### PR TITLE
Add Python 3.7 support

### PR DESCRIPTION
**Pull request by ogrisel**
I had to edit my `/home/ogrisel/miniconda3/envs/conda-forge/conda_build_config.yaml` configuration file to remove the condition on the environment variable and then I ran:

```
conda smithy rerender
```

### CODE REVIEW

**Comment by ogrisel** [comment]
@jakirkham if you are around I would love your input on this `Unsatisfiable dependencies for platform linux-64: {'numpy=1.9', 'python=3.7', 'scipy'} issue.
`

**Comment by amueller** [comment]
There is no 3.7 on condaforge, right?

**Comment by ogrisel** [comment]
It works for pandas: https://github.com/conda-forge/pandas-feedstock/tree/master/.ci_support

**Comment by ogrisel** [comment]
I guess the pinning of numpy 1.9 is problematic in this case. But it does not seem to be a problem for pandas:

https://github.com/conda-forge/pandas-feedstock/blob/master/.ci_support/linux_python3.7.yaml

But we add the scipy dependency to the mix in our case...

**Comment by jakirkham** [comment]
Both NumPy 1.9 and SciPy have been rebuilt for Python 3.7. So am not sure that is the cause. Perhaps it was a networking issue? Python 2.7 on macOS failed for this reason. Trying to give it a restart to see if that fixes it.

The other option may be `pytest` has not been rebuilt for Python 3.7 yet. FWIW most of the Python 3.7 rebuild has been folded into the compiler rebuild. So not everything may be available yet. Though it is [in progress]( https://conda-forge.org/status/ ).

**Comment by rth** [comment]
Should this be closed in favor of https://github.com/conda-forge/scikit-learn-feedstock/pull/76?

**Comment by jakirkham** [comment]
Yeah Python 3.7 is being combined with the compiler upgrade. So that is going to be the easiest path forward.

**Comment by ogrisel** [comment]
Closing in favor of #76.

**Comment by ogrisel** [comment]
Closing in favor of #76.

**Comment by ogrisel** [comment]
Closing in favor of #76.

**Comment by ogrisel** [comment]
Closing in favor of #76.

**Comment by ogrisel** [comment]
Closing in favor of #76.

**Comment by amueller** [comment]
I think @ogrisel has been abducted and is asking for help. Can anyone check on him?

**Pull request closed without merging**
