### PR TITLE
Reenables support for aarch64 and ppc64

### PR DESCRIPTION
**Pull request by thomasjpfan**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
Testing out https://github.com/scikit-learn/scikit-learn/pull/17201 to see if this works.

**Comment by thomasjpfan** [comment]
aarach64 test related to monotonic constraints are failing now: https://cloud.drone.io/conda-forge/scikit-learn-feedstock/82/1/2

**Comment by thomasjpfan** [comment]
Okay so the patch works. When https://github.com/scikit-learn/scikit-learn/pull/17201 gets merged we can build for aarch64 and ppc64.

**Comment by adrinjalali** [comment]
I think we can close this one now.

**Comment by thomasjpfan** [comment]
Yes this was just for testing.

**Pull request closed without merging**
