### PR TITLE
Update to 0.20.2

### PR DESCRIPTION
**Pull request by jnothman**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jnothman** [comment]
conda-forge-admin, please rerender

**Comment by jnothman** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Please use a fork in the future. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

**Comment by ogrisel** [comment]
@jakirkham can this be the cause of #88?

**Pull request closed without merging**
