### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by jeremiedbb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeremiedbb** [comment]
https://output.circle-artifacts.com/output/job/b4ff1d34-b905-4fb1-92e1-162fab57e5b6/artifacts/0/doc/auto_examples/release_highlights/plot_release_highlights_1_5_0.html

**Comment by jeremiedbb** [comment]
@conda-forge-admin, please rerender

**Comment by lesteve** [comment]
There is a patch issue similar to https://github.com/conda-forge/scikit-learn-feedstock/pull/254#issuecomment-2095900381. I believe https://github.com/conda-forge/scikit-learn-feedstock/blob/main/recipe/patches/0001-ignore-errors-when-tearing-down-modules.patch can be removed.

**Comment by jakirkham** [comment]
Maybe we can reuse the same strategy [planned for use in PyWavelet]( https://github.com/conda-forge/pywavelets-feedstock/pull/56/files/84d8f97fa8d6933aea7bd41dd222a9de71c00f0a#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR17-R22 ) here to simplify the cross-compilation Meson logic. This would also allow us to handle everything in `meta.yaml`

**Pull request merged**
