### PR TITLE
Release v0.20.1

### PR DESCRIPTION
**Pull request by rth**
Do not merge (yet).

This tests the upcoming 0.20.1 release from https://github.com/scikit-learn/scikit-learn/pull/12383 to make sure that tests pass and in particular that https://github.com/conda-forge/scikit-learn-feedstock/issues/77 was fixed.

### CODE REVIEW

**Comment by rth** [comment]
Continued in #81.

**Comment by rth** [comment]
This also now hangs on the test collection. All test passed 3 days ago, I'm not sure what changed.

**Comment by jnothman** [comment]
I missed that the first error there was:
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/osx-64/repodata.json>
Elapsed: -
```

**Comment by jnothman** [comment]
Rerunning the workflow seemed to result in *different* failures...?

**Comment by jnothman** [comment]
Circle took a long time to get there, but it's all green!

**Comment by jakirkham** [comment]
Appears the macOS Python 2.7 build [failed]( https://circleci.com/api/v1.1/project/github/conda-forge/scikit-learn-feedstock/794/output/104/0?file=true ). Have restarted it.

**Comment by jakirkham** [comment]
Yeah, the restarted build [also failed]( https://circleci.com/api/v1.1/project/github/conda-forge/scikit-learn-feedstock/795/output/103/0?file=true ). It seems to be hanging.

As this build is using the new compilers, which have OpenMP support, I wonder if we are oversubscribing the CPU somehow. Are there any tests that make use of OpenMP support?

**Comment by amueller** [comment]
@jakirkham not outside of blas. The weird thing was that it ran through fine when I ssh'd in and run the tests manually. I'll try to do that again, I guess?

**Comment by jnothman** [comment]
I think "deterministically" is a bit strong. It passed on a "rerun job with SSH"... but it does seem to be hanging more often than not. :(

**Pull request merged**
