### PR TITLE
Drop OpenMP libraries from `requirements/host`

### PR DESCRIPTION
**Pull request by jakirkham**
The OpenMP libraries are already added in `requirements/build`. As both libraries are configured to use `run_exports/strong` (refs: [`llvm-openmp`]( https://github.com/conda-forge/openmp-feedstock/blob/main/recipe/meta.yaml#L30-L32 ) and [`libgomp`]( https://github.com/conda-forge/ctng-compilers-feedstock/blob/bce2c2b426064e6426ccf8b1b49cdcbbd62c9ad5/recipe/meta.yaml#L453-L455 )), which adds them to `requirements/host` and `requirements/run` automatically, there is no need to add them to `requirements/host`. So this removes them.

<hr>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Julien! 🙏

Realized I forgot to re-render. Have now done that

**Comment by lesteve** [comment]
Merging, thanks!

**Comment by jakirkham** [comment]
Ofc! Thank you both 🙏

**Comment by jjerphan** [comment]
I just have realized that we need to propagate those changes to the `rc` branch as well.

**Comment by jeremiedbb** [comment]
I already did it for the 1.4 rc

**Pull request merged**
