### PR TITLE
Make a <1.0.0 release for py310

### PR DESCRIPTION
**Pull request by maresb**
I tried to install [auto-sklearn](https://github.com/conda-forge/auto-sklearn-feedstock/blob/ae567a14a1e964d15e1640c20f34dd555cdfb247/recipe/meta.yaml#L38) in a py310 env, but it needs a 0.x release which doesn't exist here for `scikit-learn`, so I figured it would be nice to have a compatible build. (This `0.24.2` version is the latest `<1` release.)

I'm hoping I'll get lucky in that this requires only minimal modifications to the feedstock... we'll see.

I'm opening this as draft so that a maintainer could create a branch for me.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
For reviewers, here is a potentially relevant [change to the requirements for osx](https://github.com/conda-forge/scikit-learn-feedstock/issues/176) adding `llvm-openmp`. (I don't understand the full context or own a mac, so hopefully someone can say whether or not I'm correct in leaving this in.)

A few initial CI failures:
* [`AttributeError: module 'uarray._uarray' has no attribute 'clear_all_globals'`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=493016&view=logs&j=3a25022a-f08c-5c04-be7d-d279a7fc48ef&t=03fcd6e6-009d-576b-db27-27f5032302f9&l=328) on Linux/aarch64/py3.9
* [`assert -14.52327257914338 == -14.523272579143388`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=493016&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=4509) on Linux/Linux64/py3.7. The two numbers differ in the second-to-last digit. At first glance this looks like an overly-sensitive test.

**Comment by maresb** [comment]
It looks like i could get a quick win here by adding `skip: true  # [py<310]`.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
All green for Python 3.10. Since this is a one-time build, I think it's not worthwhile chasing down the failures in lower versions.

I'm going to mark this as "ready for review" to get some eyes on it.

Friendly reminder: **don't merge this into main!** It needs its own `0.24.x` (or similar) branch!

**Comment by adrinjalali** [comment]
Hope this doesn't bite us. We don't really want to support 0.24.X on python=3.10

**Comment by maresb** [comment]
Oh, I'm very sorry, I didn't know. :disappointed: 

In that case perhaps we should [edit the repodata](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe) to remove the package while still keeping it available via a direct URL for reproducibility of already created environments.

**Comment by adrinjalali** [comment]
Sounds good to me @maresb :)

**Comment by maresb** [comment]
Finished.

**Comment by adrinjalali** [comment]
Thank you @maresb

**Comment by glemaitre** [comment]
Thanks

**Pull request merged**
