### PR TITLE
Drop unused backport patches [ci skip]

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/conda-forge/scikit-learn-feedstock/pull/59 ).

These patches don't appear to be used anymore in the build. They were there to fix test failures that old `scikit-learn` releases experience. As we are not using the patches and those test failures are gone, this clears them out.

### CODE REVIEW

**Comment by amueller** [comment]
thanks for the housekeeping!

**Comment by amueller** [comment]
lgtm

**Comment by jakirkham** [comment]
np. Just noticed this the other day. So figured it was time to do some tidying. 😄

**Comment by jakirkham** [comment]
Tried to skip CI, but CircleCI doesn't respect that unfortunately. I guess that can serve as a basic test that these are really not used and our eyes are not decieving us. 😆

**Pull request merged**
