### PR TITLE
CI Fixes compiler issue on windows pypy37

### PR DESCRIPTION
**Pull request by thomasjpfan**
I think this should fix the issue with windows pypy37 with 1.0.2 seen in https://github.com/conda-forge/scikit-learn-feedstock/pull/179/checks

I opened https://github.com/scikit-learn/scikit-learn/pull/22077 to fix the issue on the scikit-learn repo.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
@conda-forge-admin, please rerender

**Comment by thomasjpfan** [comment]
The pypy windows compile error is fixed with this PR. Now it is a [failure with windows+pypy](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=432702&view=logs&jobId=e5cdccbf-4751-5a24-7406-185c9d30d021&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea) after the tests passed.

**Comment by thomasjpfan** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
Is this still relevant?

**Comment by thomasjpfan** [comment]
It's likely okay to close since the issue is fixed upstream and the next release will include the fix.

**Pull request closed without merging**
