### PR TITLE
try building master, rerender

### PR DESCRIPTION
**Pull request by amueller**
Trying to build master for upcoming RC

### CODE REVIEW

**Comment by amueller** [comment]
(I just realized how stupid it was to use the master.zip reference as the build will fail as soon as master moves but at least it's working now)

**Comment by jakirkham** [comment]
Thanks for working on this. :)

Would offer to help, but it looks like you have done everything. Please let me know if that changes.

**Comment by amueller** [comment]
thanks, yeah I think we're basically set. We need to tag and branch and then update with the right tag here and we should be good to go?
Oh can you remind me how to do an RC again?

**Comment by jakirkham** [comment]
Should just be changing the base branch of the PR to the `rc` branch. Though that branch may be a bit stale, so there may be some conflicts that need to be resolved.

**Comment by jakirkham** [comment]
Addressed with PR ( https://github.com/conda-forge/scikit-learn-feedstock/pull/71 ).

**Pull request closed without merging**
