### PR TITLE
Re-render with `conda-smithy` version `1.2.0`

### PR DESCRIPTION
**Pull request by jakirkham**
Here is the result of the re-rendering. This should fix issue ( https://github.com/conda-forge/conda-smithy/issues/304 ).

cc @amueller @ogrisel

### CODE REVIEW

**Comment by amueller** [comment]
How do you rerender without losing the built matrix?

**Comment by jakirkham** [comment]
I wish I could tell you. 😒 Please see issue ( https://github.com/conda-forge/conda-smithy/issues/223 ).

If you have a reproducible case where the matrix is being dropped, we would be very appreciative if you could share it there.

**Comment by amueller** [comment]
@jakirkham hm but I don't even know how to specify the build matrix. Currently it is only in ``.travis.yml``, I guess you put it there? There is nothing specifying the build matrix in ``conda_forge.yml`` or ``meta.yml``. As everything is generated from these two files, I would expect the build matrix to be dropped...

**Comment by amueller** [comment]
to be clear, with build matrix I mean
```
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
```

**Comment by jakirkham** [comment]
Yep. We are on the same page. The matrix is set by this [line]( https://github.com/conda-forge/conda-smithy/blob/9b34e22f2d68c0ba687e0f0ed2b1e41bab16a4b1/conda_smithy/configure_feedstock.py#L366 ). Then it simply checks if `python` is a `build` and `run` dependency. It also checks if `numpy x.x` appears in `build` and `run`. If it does, one should get that matrix. The aforementioned line determines the bounds of that matrix. One can also add a custom matrix, but that isn't relevant to this discussion.

However, we have seen some cases where it doesn't happen. Unfortunately, the issue is sporadic and doesn't occur often enough for us to reproduce successfully. If you have found a reproducible case, that would be really helpful. Maybe then we can finally track this one down. 😄

**Comment by amueller** [comment]
so I ran it a bunch of times and it never generated the matrix.

**Pull request merged**
