### PR TITLE
Release 1.5.0rc1

### PR DESCRIPTION
**Pull request by jeremiedbb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeremiedbb** [comment]
@conda-forge-admin, please rerender

**Comment by jeremiedbb** [comment]
It looks like the patch can't be applied
```
Applying patch: /home/conda/recipe_root/patches/0001-ignore-errors-when-tearing-down-modules.patch
Applying patch: /home/conda/recipe_root/patches/0001-ignore-errors-when-tearing-down-modules.patch with args:
['-Np1', '-i', '/tmp/tmpvq67pp6q/0001-ignore-errors-when-tearing-down-modules.patch.native', '--binary']
checking file sklearn/metrics/tests/test_score_objects.py
Hunk #1 FAILED at 137.
1 out of 1 hunk FAILED
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/tmp/tmpvq67pp6q/0001-ignore-errors-when-tearing-down-modules.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(execute())
  File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 581, in execute
    api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3762, in build_tree
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2547, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 774, in try_download
    raise RuntimeError(
RuntimeError: Failed to download or patch source. Please see build log for info.
```

**Comment by jeremiedbb** [comment]
@jakirkham do you have an idea about what causes that ?

**Comment by ogrisel** [comment]
@jeremiedbb the patched lines were removed in https://github.com/scikit-learn/scikit-learn/commit/93f6ce994b92513a35f2ee417c77bc21d4d9fdc0. I think we can just remove this patch as it's no longer needed.

**Comment by jeremiedbb** [comment]
Let's merge without the osx arm builds and figure out later how to handle meson + cross compilation

**Pull request merged**
