### PR TITLE
Release 0.18.2 (NumPy 1.11)

### PR DESCRIPTION
**Pull request by jakirkham**
Releases 0.18.2 built with NumPy 1.11.

Other 0.18.2 Numpy builds:

* NumPy 1.13: https://github.com/conda-forge/scikit-learn-feedstock/pull/50
* NumPy 1.12: https://github.com/conda-forge/scikit-learn-feedstock/pull/51

cc @amueller

### CODE REVIEW

**Comment by jakirkham** [comment]
Feedback on this?

**Comment by jakirkham** [comment]
Thanks for taking a look @ogrisel. Is there feedback from others or are we good to merge? @lesteve?

Also would be good if others double check the other 2 PRs here.

**Comment by jakirkham** [comment]
Went ahead and merged these to get the new release out. Given these have been pretty quiet for the past few days, I'm guessing we are happy with the result or at least not worried about it. If that's not the case, please feel free to let me know. Not to mention they are pretty minor in nature (i.e. version bump and slight tweak to the existing test patch). Am more than happy to discuss changes that may be needed.

**Comment by ogrisel** [comment]
Thanks, indeed that should be quite safe.

**Pull request merged**
