### PR TITLE
MNT: Re-rendered with conda-build 3.21.4, conda-smithy 3.10.3, and co…

### PR DESCRIPTION
**Pull request by mattip**
…nda-forge-pinning 2021.07.21.07.43.34

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

updated the build to 1 to get pypy windows builds

### CODE REVIEW

**Comment by mattip** [comment]
I don't see the pypy windows 3.7 build in the set of builds.

**Comment by h-vetinari** [comment]
The migrator was blocked on getting to this feedstock due to scipy. It arrived now: #156.

**Comment by mattip** [comment]
Closing in favor of the migrator PRs #156, #157 (why are there two?)

**Comment by h-vetinari** [comment]
> (why are there two?)

This feedstock has a second branch [registered](https://github.com/conda-forge/scikit-learn-feedstock/blob/master/conda-forge.yml#L5-L7) for migrations.

**Pull request closed without merging**
