### PR TITLE
Release 0.24.2

### PR DESCRIPTION
**Pull request by glemaitre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by glemaitre** [comment]
@conda-forge-admin, please rerender

**Comment by glemaitre** [comment]
The `ppc-cpython` (3.6/3.7) build freezes when compiling and finishes with:

```
...
compile options: '-I$PREFIX/lib/python3.6/site-packages/numpy/core/include -I$PREFIX/include/python3.6m -c'
extra options: '-fopenmp'
powerpc64le-conda-linux-gnu-cc: sklearn/utils/_cython_blas.c
```

The builds lasted 20 minutes which is below the duration of the previous builds that succeeded, so it is probably not a timeout.
We should note that NumPy has been updated from 1.16 to 1.17 between the release PRs for scikit-learn 0.24.1 and 0.24.2. However, since there are no errors it might not be linked.

**Comment by glemaitre** [comment]
@jakirkham @ocefpaf Do you have a clue of what could be the root of the issue?

**Comment by ogrisel** [comment]
Personally I would be in favor of **not** blocking the 0.24.2 release because of the PPC failures.

**Comment by glemaitre** [comment]
Regarding the `pypy` build that is failing, it seems to be due to a timeout in this case:

```
...
[42/51] Cythonizing sklearn/utils/_fast_dict.pyx

[43/51] Cythonizing sklearn/utils/_logistic_sigmoid.pyx

[44/51] Cythonizing sklearn/utils/_openmp_helpers.pyx

[45/51] Cythonizing sklearn/utils/_random.pyx

/home/conda/feedstock_root/.scripts/build_steps.sh: line 74:   560 Killed                  conda $BUILD_CMD "${RECIPE_ROOT}" -m "${CI_SUPPORT}/${CONFIG}.yaml" --suppress-variables ${EXTRA_CB_OPTIONS:-} --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"

The command "if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi" exited with 137.
```

**Review by ogrisel — APPROVED** [review]

**Comment by glemaitre** [comment]
Uhm we also have a timeout on the Python 3.6 Numpy 1.18 aarch64 (after 99% of the test completed :)). The issue is that the file is then not uploaded. This is a pity. I don't know how we can solve this (skip the tests when uploading on the server?)

**Comment by jakirkham** [comment]
Would just restart. Some ARM jobs get assigned to nodes with less resources than others. Unfortunately it is just luck which node a build lands on. Restarting should give it another try and likely get a node with more resources

**Comment by jakirkham** [comment]
As to the Travis CI failures, mentioned them here ( https://gitter.im/conda-forge-ppc64le/Lobby?at=6089a86bc29ca4049cddff38 )

**Comment by jakirkham** [comment]
A different ARM build failed. However the one that failed before passed. So it looks like all of those packages are up now.

Going to try restarting Travis CI.

**Comment by jakirkham** [comment]
Looks like Travis CI passed! 😄 🎉

So I think all the packages are published now. Please let us know if you run into other issues 🙂

**Comment by glemaitre** [comment]
Thanks a lot, @jakirkham. This is nice to start the day with fixed packaging :)

**Pull request merged**
