### PR TITLE
fix failure due to deleting non existing cblas.h

### PR DESCRIPTION
**Pull request by fhoehle**
This PR fixes https://github.com/conda-forge/scikit-learn-feedstock/issues/103. Starting with libcblas-3.8.0-11_openblas no header file are placed into the include directory.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by rth** [comment]
As far as I understood from the conda-forge perspective it shouldn't matter which blas was used for build, as a different one could be used at run time due to ABI compatibility? So this shouldn't change anything with respect to produced artifacts, and maybe there is no need to increment the build number? 

Otherwise the fix looks good.

**Comment by fhoehle** [comment]
> As far as I understood from the conda-forge perspective it shouldn't matter which blas was used for build, as a different one could be used at run time due to ABI compatibility? So this shouldn't change anything with respect to produced artifacts, and maybe there is no need to increment the build number?

Yes you are correct, build number is not changed anymore.

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by fhoehle** [comment]
Both test failures (linux linux_python3.6/7):

```

=================================== FAILURES ===================================
_______________________________ test_lda_predict _______________________________

    def test_lda_predict():
        # Test LDA classification.
        # This checks that LDA implements fit and predict and returns correct
        # values for simple toy data.
        for test_case in solver_shrinkage:
            solver, shrinkage = test_case
            clf = LinearDiscriminantAnalysis(solver=solver, shrinkage=shrinkage)
            y_pred = clf.fit(X, y).predict(X)
            assert_array_equal(y_pred, y, 'solver %s' % solver)
    
            # Assert that it works with 1D data
            y_pred1 = clf.fit(X1, y).predict(X1)
            assert_array_equal(y_pred1, y, 'solver %s' % solver)
    
            # Test probability estimates
            y_proba_pred1 = clf.predict_proba(X1)
            assert_array_equal((y_proba_pred1[:, 1] > 0.5) + 1, y,
                               'solver %s' % solver)
            y_log_proba_pred1 = clf.predict_log_proba(X1)
            assert_array_almost_equal(np.exp(y_log_proba_pred1), y_proba_pred1,
>                                     8, 'solver %s' % solver)
E           AssertionError: 
E           Arrays are not almost equal to 8 decimals
E           solver svd
E           Mismatch: 16.7%
E           Max absolute difference: 5.9604645e-08
E           Max relative difference: 4.7683716e-07
E            x: array([[9.9999994e-01, 1.1253517e-07],
E                  [9.9966466e-01, 3.3535002e-04],
E                  [9.9966466e-01, 3.3535002e-04],...
E            y: array([[9.99999881e-01, 1.12535155e-07],
E                  [9.99664664e-01, 3.35350138e-04],
E                  [9.99664664e-01, 3.35350138e-04],...

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/site-packages/sklearn/tests/test_discriminant_analysis.py:82: AssertionError
=============================== warnings summary ===============================
```

 are known upstream issues https://github.com/scikit-learn/scikit-learn/issues/14513 which were addressed by https://github.com/scikit-learn/scikit-learn/pull/14978 and will be available with next `scikit-learn` release.

**Comment by fhoehle** [comment]
@rth the drone build was canceled after one hour. Are you able to restart it?

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by rth** [comment]
CI is still failing. If you are still interested in applying this, might be easier to take the state of the current master as reference (that was green just now), instead of re-rendering.

**Comment by rth** [comment]
Closing same as the original issue https://github.com/conda-forge/scikit-learn-feedstock/issues/103#issuecomment-668000055

**Pull request closed without merging**
