### PR TITLE
release 0.20.1

### PR DESCRIPTION
**Pull request by amueller**
follow up on #80 using actual release

### CODE REVIEW

**Comment by amueller** [comment]
build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7 timed out :( I restarted in the unlikely event it was a fluke

**Comment by jnothman** [comment]
Strangely, the automatic https://github.com/conda-forge/scikit-learn-feedstock/pull/82 also failed on a [single run](https://circleci.com/gh/conda-forge/scikit-learn-feedstock/644?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but not py2.7. (I don't have permissions to restart that run.)

**Comment by amueller** [comment]
but that one was a server timeout, so really a fluke.

**Comment by jakirkham** [comment]
@jnothman, if you add yourself as a maintainer, then the bot will add you and give you permissions.

**Comment by jnothman** [comment]
Thanks @jakirkham, it's not essential to me that I am authorised, but I suppose it doesn't hurt.

**Comment by jnothman** [comment]
(After all, I can do things while the Europeans and Americans are sleeping :P)

**Comment by amueller** [comment]
Should we announce once wheels and conda-forge is up?

**Comment by amueller** [comment]
hm
```
============================= test session starts ==============================
platform darwin -- Python 2.7.15, pytest-3.2.2, py-1.6.0, pluggy-0.4.0
rootdir: $SRC_DIR, inifile:
collected 10159 items

Too long with no output (exceeded 10m0s)
```

**Comment by jakirkham** [comment]
Do you happen to recall, which builds failed? Were these all on the macOS CircleCI workers or were some of them Linux?

**Comment by amueller** [comment]
I guess I meant let's see if this doesn't time out at least.

**Comment by amueller** [comment]
ping @ogrisel did I do the thread thing right? This doesn't look good :-/

**Comment by amueller** [comment]
@jakirkham only OS X Python 2.7

**Comment by amueller** [comment]
ssh'ed in and got
```
================================================================== 10037 passed, 119 skipped, 3 xfailed, 1147 warnings in 641.86 seconds ===================================================================
```
in the same environment. That's helpful.

**Comment by lesteve** [comment]
I don't have any good suggestions I am afraid ... the only one I have is to try to add `-v` to the pytest command to see if that helps the build printing some output. If it still gets stuck at one point during the tests, the `-v` output may help figure out where.

**Comment by amueller** [comment]
Yeah seems like a good idea. I'll be offline for the holidays soon, though. and it doesn't even print the dots for some reason? it's weird. I just changed to OPENPLAS_NUM_THREADS=1 to see if it has any effect at all.

**Comment by amueller** [comment]
slightly slower but also runs through fine... hum

**Comment by rth** [comment]
It's strange though that #80 passed, the v0.20.1 tag only has a few additional commits. Will re-try that one, as I can't trigger build here either.

**Comment by rth** [comment]
> I just changed to OPENPLAS_NUM_THREADS=1 [...] slightly slower but also runs through fine... 

Tried that in https://github.com/conda-forge/scikit-learn-feedstock/pull/80 -- it still hangs on test collection (and one other job had an HTTP timeout).

Should we merge that one to at least release the other Python versions / OS, then investigate ?

**Comment by ogrisel** [comment]
+1

Le sam. 24 nov. 2018 à 1:13 PM, Roman Yurchak <notifications@github.com> a
écrit :

**Comment by amueller** [comment]
sure. conda main channel has already released. I'll be mostly offline this weekend.

**Comment by rth** [comment]
Someone will need to press the button then (in the other PR). I don't have commit rights.

**Comment by jschueller** [comment]
I prefer consistency, I dont like incomplete prs being merged where  one flavor might end up left behind like in #77.

**Pull request closed without merging**
