### PR TITLE
Release 0.24.0rc1

### PR DESCRIPTION
**Pull request by ogrisel**
For the record, here is what I did to generate this PR:

- Reused the `recipe/meta.yaml` file from the master branch of the feedstock
- Reused the content of `.ci_support/migrations` from the master branch of the feedstock (should not be needed in the future #139)
- Update version number and sha256sum for 0.24.0rc1
- Reset build number to 0
- Add `recipe/conda_build_config.yaml` to target the `scikit-learn_rc` label as explained in [CFEP 5](https://github.com/conda-forge/cfep/blob/master/cfep-05.md)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ogrisel** [comment]
@conda-forge-admin, please rerender

**Comment by ogrisel** [comment]
Hum it's missing Python 3.9 support. I am not sure where this is defined.

**Comment by ogrisel** [comment]
@conda-forge-admin, please rerender

**Comment by ogrisel** [comment]
I don't understand why the re-render did not add the CI config for building on CPython 3.9.

**Comment by ogrisel** [comment]
@conda-forge-admin, please rerender

**Comment by ogrisel** [comment]
It seems to work as expected. Thanks for the help @xhochy!

**Comment by adrinjalali** [comment]
Don't we wait for the bot to pick up the tag and create the release PR?

**Comment by ogrisel** [comment]
> Don't we wait for the bot to pick up the tag and create the release PR?

It does not work for RC apparently. This is manual and a bit different than the usual.

**Comment by ogrisel** [comment]
@adrinjalali merge when green?

**Comment by ogrisel** [comment]
Hum we got crashes in PyPy for x86_64 macOS:

```
=================================== FAILURES ===================================
___________________ compose/tests/test_column_transformer.py ___________________
[gw1] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw1' crashed while running 'compose/tests/test_column_transformer.py::test_column_transformer_get_feature_names'
_______________ feature_extraction/tests/test_dict_vectorizer.py _______________
[gw0] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw0' crashed while running 'feature_extraction/tests/test_dict_vectorizer.py::test_dictvectorizer[True-True-int-True]'
____________________________ tests/test_pipeline.py ____________________________
[gw2] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw2' crashed while running 'tests/test_pipeline.py::test_feature_union_parallel'
__________________________ tests/test_calibration.py ___________________________
[gw4] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw4' crashed while running 'tests/test_calibration.py::test_calibration_pipeline'
_______________ feature_extraction/tests/test_dict_vectorizer.py _______________
[gw3] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw3' crashed while running 'feature_extraction/tests/test_dict_vectorizer.py::test_dictvectorizer[True-True-float32-True]'
_______________ feature_extraction/tests/test_dict_vectorizer.py _______________
[gw5] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw5' crashed while running 'feature_extraction/tests/test_dict_vectorizer.py::test_dictvectorizer[True-True-int-False]'
_______________ feature_extraction/tests/test_dict_vectorizer.py _______________
[gw7] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw7' crashed while running 'feature_extraction/tests/test_dict_vectorizer.py::test_dictvectorizer[True-True-float32-False]'
____________________________ tests/test_pipeline.py ____________________________
[gw6] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw6' crashed while running 'tests/test_pipeline.py::test_feature_union_feature_names'
_______________ feature_extraction/tests/test_dict_vectorizer.py _______________
[gw9] darwin -- Python 3.6.9 $PREFIX/bin/python
worker 'gw9' crashed while running 'feature_extraction/tests/test_dict_vectorizer.py::test_dictvectorizer[True-True-int16-False]'
=============================== warnings summary ===============================
```

It could be caused by a memory usage problem (OOM killer) maybe?

I would be in favor of merging this PR anyway and try to find a solution before 0.24.0 final.

**Comment by adrinjalali** [comment]
Do I understand correctly that this PR is doing a few things, including adding support for cases which we didn't have before? It's kinda hard for me to review the PR with so many changes in one place. Could you maybe explain them or separate them if possible?

**Comment by ogrisel** [comment]
Look at the changes I made in my manual commits, they are simple. Ignore the changes generated by the commit of the re-render bot.

**Comment by ogrisel** [comment]
Since this is a PR for an RC release, it's targeting the `rc` branch, not master. This is why I had to fetch information from the master recipe.

The only commit that is strictly related to releasing 0.24.0rc1 is: 261af92c2051ab7595dd2448745fd4688ca8c856. The rest synchronizing the rc branch with config that was already merged in master and re-rendering.

**Comment by adrinjalali** [comment]
Oh I see, now it makes sense. I personally don't see it necessary to release the conda-forge builds for the RCs, but since you've done it, why not :) Thanks.

**Comment by ogrisel** [comment]
> Oh I see, now it makes sense. I personally don't see it necessary to release the conda-forge builds for the RCs, but since you've done it, why not :) Thanks.

I thought so too at the beginning but then I changed my mind as it's a good way to check that our conda-forge setup will be working for 0.24.0 final (including PyPy and maybe ARM/PPCle packages and such which we do not yet include in our PyPI release process).

**Comment by adrinjalali** [comment]
Then happy to merge and fix the potential issues before the release :) feel free to merge whenever you think appropriate.

**Comment by ogrisel** [comment]
Let's wait the re-run of the failed PyPy / macOS build to see if it crashed again.

**Comment by ogrisel** [comment]
It crashed again. Will investigate later. Let's merge to get the RC for all the other platforms.

**Pull request merged**
