### PR TITLE
0.19.1 release

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Need to update the checksum too. 😉

**Comment by jakirkham** [comment]
Also will want to reset the build number to `200`.

**Comment by jnothman** [comment]
Thanks @amueller for completing the release!

**Comment by jakirkham** [comment]
Thanks @amueller.

**Comment by amueller** [comment]
thanks @jnothman for doing all the work ;)

**Comment by jnothman** [comment]
Not quite all. @lesteve deserves a lot of credit. Also we've had some great
help in general from @qinhanmin2014 and @rth.

**Comment by amueller** [comment]
Yes, I did see @lesteve was busy, and also @qinhanmin2014 and @rth. Thanks folks!

**Pull request merged**
