### PR TITLE
1.0 release

### PR DESCRIPTION
**Pull request by adrinjalali**
testing the release builds

### CODE REVIEW

**Comment by ogrisel** [comment]
You need to read the dependency on py37 that was only pushed to the `rc` branch.

**Comment by adrinjalali** [comment]
@conda-forge-admin, please re-render

**Comment by adrinjalali** [comment]
won't merge this and will wait for the bot to detect the tag. closing since it's tested now.

**Comment by adrinjalali** [comment]
Oh now, actually need this for the python support update

**Review by ogrisel — APPROVED** [review]
LGTM (but the PR should not be merge as long as the final tag has not been pushed and the digest update).

**Comment by adrinjalali** [comment]
@ogrisel the tag is published, and this PR uses the tag now. I'm not sure what you mean by the digest. I was planning to merge this one and publish the wheels at the same time.

**Comment by ogrisel** [comment]
Ok I had not realized this was already using the tag.

**Comment by adrinjalali** [comment]
The travis fail is happening about half the time, and it's kind of a time out. I wouldn't wait for that to be fixed, and hopefully once merged it actually manages to finish the test/build. If not, we can ignore more tests for that platform.

The fail is always on 

     CONFIG=linux_ppc64le_numpy1.19python3.7.____73_pypypython_implpypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le

**Comment by adrinjalali** [comment]
cpython 3.7 on aarch64 is also timeout on circleCI.

**Comment by adrinjalali** [comment]
It really depends on the machine it seems, the tests pass if you run the again (at least they have in the past)

**Comment by ogrisel** [comment]
I agree I would not block the release for this.

**Pull request merged**
