### PR TITLE
Build scikit-learn 0.18rc1

### PR DESCRIPTION
**Pull request by ogrisel**

### CODE REVIEW

**Comment by ogrisel** [comment]
@jakirkham is there a way to tell conda-forge to use git to fetch the source at tag 0.18rc1 instead of the source tarball from pypi? I would like to do a sync release of the sdist on PyPI and the scikit-learn on the conda-forge channel.

**Comment by ocefpaf** [comment]
> is there a way to tell conda-forge to use git to fetch the source at tag 0.18rc1 instead of the source tarball from pypi?

You can change

```yaml
 source:
   fn: scikit-learn-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/s/scikit-learn/scikit-learn-{{ version }}.tar.gz
   md5: a2f8b877e6d99b1ed737144f5a478dfc
```

to 

```yaml
 source:
   fn: scikit-learn-{{ version }}.tar.gz
   url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
   sha256: 101a3d7c9bd40fe2184049d460888f5af26f5ca2a8dfd69b4149ca08ce5db618
```

But we never settle on a simple way to make release candidates on `conda-forge`. If you are interested please join the discussion: https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG

**Comment by ocefpaf** [comment]
@ogrisel are you working on a fork? I noticed that `Travis-CI` started twice and that happens when the PR is from the same repo instead of a fork. That is not OK in `conda-forge` because, if the CIs are successful, you will upload the binary before the merge.

**Comment by amueller** [comment]
@ogrisel I already had the changes in https://github.com/scikit-learn/scikit-learn-feedstock. Is your goal to build the rc in the main conda-forge channel? That seems like a bad idea to me.

**Comment by ocefpaf** [comment]
>  Is your goal to build the rc in the main conda-forge channel? That seems like a bad idea to me.

it is not once we figure out a proper way to ship them in isolated channels. We are doing this already for Python 3.6 and matplotlib RCs BTW. `conda-forge` only needs to find a "standardize" way to do it so other feedstocks can implement the same.

**Comment by amueller** [comment]
@ocefpaf but is that available now? This script ships the current RC to all conda-forge users now, right?

**Comment by ogrisel** [comment]
> @ogrisel are you working on a fork? I noticed that Travis-CI started twice and that happens when the PR is from the same repo instead of a fork. That is not OK in conda-forge because, if the CIs are successful, you will upload the binary before the merge.

Indeed I did it from the github web editor UI instead of using the git client. I will never do it again :)

**Comment by ocefpaf** [comment]
> @ocefpaf but is that available now?

Like I mention above we haven't come up with a way to do this for every feedstock yet. But we are testing this with matplotlib and Pythnon 3.6. For example, you can get Python 3.6 via the channel label `conda-forge/label/prerelease` with

```shell
conda create --yes -n PY36 -c conda-forge/label/prerelease python=3.6
```

> This script ships the current RC to all conda-forge users now, right?

Not sure what you mean. But the paclage would be available in that label for everybody.

**Comment by ogrisel** [comment]
Closing this PR as it is done from a bad branch. I let @amueller try to trigger the final build.

**Comment by ogrisel** [comment]
> Is your goal to build the rc in the main conda-forge channel? That seems like a bad idea to me.

Why? Because of openblas? Fine with using a dedicated channel.

**Comment by amueller** [comment]
@ogrisel no because I didn't see you specify a separate label. I don't want to ship an RC to people without opting in.
@ocefpaf this PR didn't specify a label, I think (or I missed it) so everybody would have gotten the RC by default, right? I didn't want that to happen.

**Comment by ocefpaf** [comment]
> @ocefpaf this PR didn't specify a label, I think (or I missed it) so everybody would have gotten the RC by default, right? I didn't want that to happen.

That is why I mentioned above

> But we never settle on a simple way to make release candidates on conda-forge. If you are interested please join the discussion: https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG

conda-forge is still discussing how to enable RC builds on the feedstocks.

**Comment by jakirkham** [comment]
Yeah, I know it is not standard, but configuring a feedstock outside of conda-forge is proving a bit tricky and I'm learning about it as we do it.

Would kind of rather we do the RC at conda-forge if there isn't any opposition to it (even though it isn't standard). I'm familiar with this workflow and it is not difficult. We can put it under a different label without issues. Thoughts?

**Pull request closed without merging**
