### PR TITLE
Update to 0.18.1

### PR DESCRIPTION
**Pull request by ocefpaf**
```
[MRG + 1] More versionadded everywhere! (#7403)

* insert versionadded versionchanged directives in docstrings for 0.18

indicate where exception classes were moved from

* moved versionadded in the proper places
```

### CODE REVIEW

**Comment by jakirkham** [comment]
We need another one like this PR'd against `master_np1.10` as we had to break the NumPy version matrix apart to fit on CIs.

**Comment by jakirkham** [comment]
Seeing a testing failure. Thoughts @amueller ?

```python
======================================================================
FAIL: sklearn.linear_model.tests.test_ridge.test_dense_sparse(<function _test_ridge_loo at 0x7fb987b7c0c8>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/sklearn/linear_model/tests/test_ridge.py", line 456, in check_dense_sparse
    ret_sparse = test_func(SPARSE_FILTER)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/sklearn/linear_model/tests/test_ridge.py", line 329, in _test_ridge_loo
    assert_almost_equal(errors, errors2)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/numpy/testing/utils.py", line 523, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 99.5%)
 x: array([  8.3413422e+04,   3.0406340e+04,   1.3073753e+04,   5.8119438e+02,
         2.6840821e+04,   4.3934636e+04,   3.0284908e+04,   4.5244538e+04,
         3.3800678e+04,   9.0488797e+03,   5.5727766e+04,   2.9894065e+04,...
 y: array([ 83413.4220579,  30715.633919 ,  14756.6103169,   5232.4120662,
        30524.4660113,  54211.4551856,  40359.6205922,  48120.5271189,
        20053.0376978,   5861.809863 ,  67582.6551838,  22327.2661592,...

----------------------------------------------------------------------
```

ref: https://circleci.com/gh/conda-forge/scikit-learn-feedstock/50

**Comment by amueller** [comment]
that doesn't look great. Is that all platforms?

**Comment by jakirkham** [comment]
Not sure. Haven't gotten the Travis CI/Mac results yet. Currently just seeing on CircleCI so Linux.

**Comment by jakirkham** [comment]
We get a test failure, but not the same one, on Travis CI. Seems to be the same error on all Python versions (2.7, 3.4, and 3.5).

```python
======================================================================

FAIL: sklearn.manifold.tests.test_t_sne.test_n_iter_without_progress

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/sklearn/manifold/tests/test_t_sne.py", line 584, in test_n_iter_without_progress

    "last 2 episodes. Finished.", out)

AssertionError: 'did not make any progress during the last 2 episodes. Finished.' not found in '[t-SNE] Computing pairwise distances...\n[t-SNE] Computed conditional probabilities for sample 100 / 100\n[t-SNE] Mean sigma: 0.765549\n[t-SNE] Iteration 25: error = 13.5941929, gradient norm = 0.0787243\n[t-SNE] Iteration 50: error = 13.3894499, gradient norm = 0.0770499\n[t-SNE] Iteration 75: error = 17.2619819, gradient norm = 0.2986331\n[t-SNE] Iteration 100: error = 16.4814787, gradient norm = 0.0060466\n[t-SNE] KL divergence after 100 iterations with early exaggeration: 16.481479\n[t-SNE] Iteration 125: error = 2.3524479, gradient norm = 0.0015101\n[t-SNE] Iteration 150: error = 2.2885583, gradient norm = 0.0013097\n[t-SNE] Iteration 175: error = 2.2739044, gradient norm = 0.0012655\n[t-SNE] Iteration 200: error = 2.2700430, gradient norm = 0.0012547\n[t-SNE] Iteration 225: error = 2.2689857, gradient norm = 0.0012518\n[t-SNE] Iteration 250: error = 2.2686934, gradient norm = 0.0012510\n[t-SNE] Iteration 275: error = 2.2686124, gradient norm = 0.0012508\n[t-SNE] Iteration 300: error = 2.2685899, gradient norm = 0.0012507\n[t-SNE] Iteration 325: error = 2.2685837, gradient norm = 0.0012507\n[t-SNE] Iteration 350: error = 2.2685820, gradient norm = 0.0012507\n[t-SNE] Iteration 375: error = 2.2685815, gradient norm = 0.0012507\n[t-SNE] Iteration 400: error = 2.2685814, gradient norm = 0.0012507\n[t-SNE] Iteration 425: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 450: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 475: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 500: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 525: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 550: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 575: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 600: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 625: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 650: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 675: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 700: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 725: error = 2.2685813, gradient norm = 0.0012507\n[t-SNE] Iteration 725: error difference 0.000000. Finished.\n[t-SNE] Error after 725 iterations: 16.481479\n'

----------------------------------------------------------------------
```

xref: https://travis-ci.org/conda-forge/scikit-learn-feedstock/jobs/175803688

**Comment by amueller** [comment]
That's weird, I haven't seen this one before.

**Comment by lesteve** [comment]
Actually that's the same failure as https://github.com/scikit-learn/scikit-learn/issues/7921.

**Comment by jschueller** [comment]
seems you need to backport https://github.com/scikit-learn/scikit-learn/pull/8154/commits/3933130596413dfba46b69f9b8bef8be1c5a5dc1

**Comment by jakirkham** [comment]
Is that correct, @lesteve?

**Comment by lesteve** [comment]
>> seems you need to backport scikit-learn/scikit-learn@3933130

> Is that correct, @lesteve?

Well scikit-learn/scikit-learn@3933130 would probably the error in https://github.com/conda-forge/scikit-learn-feedstock/pull/24#issuecomment-260456793 but that would not be 0.18.1 any more. The plan is to make a 0.19 release in the not too distant future, but there is no strong guarantee about when it is going to happen.

Still, I think we should make 0.18.1 available on conda-forge even if there are errors during the tests, is that something that is doable within the conda-forge framework ? Do we need everything to be green (by for example amending temporarily `meta.yml` to skip the tests) to upload the conda package to conda-forge ?

**Comment by jakirkham** [comment]
The typical way we handle this problem is to apply the needed patches to fix the failures before releasing. Are you ok with that?

**Comment by lesteve** [comment]
> The typical way we handle this problem is to apply the needed patches to fix the failures before releasing. Are you ok with that?

That seems fine in general but it looks like we missed our chance for 0.18.1 (and we probably need to think about testing our beta + rc next time on conda-forge).

What I was wondering though was: is there a way to upload the 0.18.1 package on conda-forge regardless of the errors during the test ?

**Comment by jakirkham** [comment]
The CIs have to pass to upload binaries.

Suppose we could skip the tests, but I'm not comfortable skipping all of them. Though I could be persuaded to skip this one test, but it is probably just easier to patch it if there is a fix.

**Comment by jakirkham** [comment]
> we probably need to think about testing our beta + rc next time on conda-forge

👍 We definitely should chat about this when it gets closer to that time. We did do an RC or two for 0.18 and have a mechanism for doing this on this feedstock.

**Comment by jschueller** [comment]
superceded by #40

**Pull request closed without merging**
